version: '3.9'
services:
    db:
        platform: linux/amd64
        image: mysql:5.7
        restart: always
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: 'bds'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_PASSWORD: ""
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pmab
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8082:80
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: 'bds29'
        ports:
            - "8803:80"
        volumes:
            - ./:/var/www/html
            - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
